[project]
name = "uidm_client"
version = "0.10"
authors = [
  { name="Dominik Åukasik", email="dmcode@outlook.com" },
]
description = "A Very Simple UIDM Client"
readme = "README.md"
requires-python = ">=3.7"

[build-system]
requires = ["setuptools>=40.9.0"]
build-backend = "setuptools.build_meta"
